<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="AuthService.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sinbas.Domain\Sinbas.Domain.fsproj" />
  </ItemGroup>

</Project>
